encoder_dim: 256
observation_dim: 6
torque_dim: 6
angle_dim: 6
picture_dim: 22500
action_dim: 6
share_dim: 48

one_hot_torque_dim: 42
one_hot_angle_dim: 42
num_stack: 3
frameskip: 5
crop_percent: 0.1
conv_bottleneck: 128
batch_size: 32

noc : 1
nocrop: 0
resized_height_v: 75
resized_width_v: 100 
resized_height_t: 60 #75 #150
resized_width_t: 80 #100 #200

ROI: 0
mask_height_t: 300
mask_height_v: 480
mask_width_t: 300 
mask_width_v: 550 

ablation: I_T_A
encoder: mlp
gamma: 0.9
gradient_clip_val: 0.5 
lr: 1e-4
num_heads: 8
norm_audio: True
# m_mha no_mha 
use_way : m_mha
# 0 (no pos) /  1 (pos)
use_pos: 1
# 0 (no one_hot) /  1 (one_hot)
use_one_hot: 1
task: "I_T_A"
aux_multiplier: 1.0
epochs: 100
num_trials: 100
train: True
## loss
a_loss : 1
### 
f_loss : 1
loss: huber
delta: 0.2
fix_loss_delta: 0.1

## action type
dis_actions : 0 # False


## train
train_data: exp_apple14、exp_dragon14、exp_durian14、exp_flog14、exp_jar14、exp_mango14
## val 
val_data: exp_peach3、exp_apple3、exp_dragon3、exp_flog3

## test 
ckpt:  best_policy/05-23-21:04:30j_f_vf_frog_dragon_f_a_l1loss-epoch=5-step=2304.ckpt
# train: False
